# Generated by Django 3.2.4 on 2021-09-16 10:31

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=200)),
                ('content', models.TextField(max_length=20000)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
